"""empty message

Revision ID: 0e32457bad30
Revises: 86ec285a2fb1
Create Date: 2025-11-05 21:56:40.967125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e32457bad30'
down_revision = '86ec285a2fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipment_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('date')
        batch_op.drop_column('shipment_number')

    # ### end Alembic commands ###
