"""empty message

Revision ID: 1e8297b86d1b
Revises: dfc507d6f799
Create Date: 2025-10-11 13:54:53.754040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e8297b86d1b'
down_revision = 'dfc507d6f799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('html_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('html_description', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
