"""empty message

Revision ID: 26ab14a30d1d
Revises: 1883fd0ccdea
Create Date: 2025-10-28 16:26:35.725085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26ab14a30d1d'
down_revision = '1883fd0ccdea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credentials_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_order_credentials_id', 'credentials', ['credentials_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_credentials_id', type_='foreignkey')
        batch_op.drop_column('credentials_id')

    # ### end Alembic commands ###
