"""empty message

Revision ID: 86ec285a2fb1
Revises: dec4d21cc3fb
Create Date: 2025-11-03 22:36:54.208850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ec285a2fb1'
down_revision = 'dec4d21cc3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.Column('credentials_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credentials_id'], ['credentials.id'], name='fk_destinations_credentials_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destinations')
    # ### end Alembic commands ###
