"""empty message

Revision ID: f32e9ccaa25b
Revises: 0e32457bad30
Create Date: 2025-11-10 13:35:25.850905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32e9ccaa25b'
down_revision = '0e32457bad30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statistic_string', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.drop_column('statistic_string')

    # ### end Alembic commands ###
